repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/bwbaugh/haskell-pre-commit-hooks
  rev: v0.2.1
  hooks:
  - id: hlint
    args: ["-X", "QuasiQuotes"]
  - id: stylish-haskell
