name: haskell-linear
version: 0.1.0.0
github: "epgui/haskell-linear"
license: PublicDomain
author: "Guillaume Pelletier"
maintainer: "guigui.p@gmail.com"

extra-source-files:
- README.md

dependencies:
- base >= 4.15 && < 5
- parsec >= 3.1 && < 4

library:
  source-dirs: src

executables:
  haskell-linear-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: ["-threaded", "-rtsopts", "-with-rtsopts=-N", "-fllvm"]
    dependencies:
    - haskell-linear

tests:
  haskell-linear-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: ["-threaded", "-rtsopts", "-with-rtsopts=-N", "-fllvm"]
    dependencies:
    - haskell-linear
